# Generated by Django 4.1.7 on 2023-04-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ename', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mobile', models.IntegerField()),
                ('salary', models.FloatField()),
                ('address', models.TextField()),
                ('dept', models.IntegerField()),
            ],
        ),
    ]
